"""Type stubs for the ``pulp._rustcore`` Rust extension module (PyO3)."""

from __future__ import annotations

class Category:
    """Variable category: continuous, integer, or binary."""

    Continuous: Category
    Integer: Category
    Binary: Category
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class Sense:
    """Constraint sense: <=, ==, >=."""

    LessEqual: Sense
    Equal: Sense
    GreaterEqual: Sense
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class ObjSense:
    """Objective sense: minimize or maximize."""

    Minimize: ObjSense
    Maximize: ObjSense
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class Variable:
    """Handle to a variable stored inside a Rust ``ModelCore``."""

    @property
    def name(self) -> str: ...
    @property
    def lb(self) -> float: ...
    @property
    def ub(self) -> float: ...
    @property
    def category(self) -> Category: ...
    @property
    def value(self) -> float | None: ...
    @property
    def dj(self) -> float | None: ...
    def id(self) -> int: ...
    def set_value(self, v: float) -> None: ...
    def set_lb(self, lb: float) -> None: ...
    def set_ub(self, ub: float) -> None: ...
    def set_name(self, name: str) -> None: ...
    def set_dj(self, v: float) -> None: ...

class Constraint:
    """Handle to a constraint stored inside a Rust ``ModelCore``."""

    @property
    def name(self) -> str: ...
    @property
    def pi(self) -> float | None: ...
    @property
    def slack(self) -> float | None: ...
    @property
    def sense(self) -> Sense: ...
    @property
    def rhs(self) -> float: ...
    def id(self) -> int: ...
    def set_name(self, name: str) -> None: ...
    def set_pi(self, v: float) -> None: ...
    def set_slack(self, v: float) -> None: ...
    def items(self) -> list[tuple[Variable, float]]: ...

class AffineExpr:
    """Affine expression: sum_i coeff_i * x_i + constant."""

    def __init__(self) -> None: ...
    @staticmethod
    def from_variable(var: Variable) -> AffineExpr: ...
    @staticmethod
    def from_constant(value: float) -> AffineExpr: ...
    @property
    def constant(self) -> float: ...
    @property
    def sense(self) -> Sense | None: ...
    @property
    def name(self) -> str | None: ...
    def add_term(self, var: Variable, coeff: float) -> None: ...
    def set_constant(self, constant: float) -> None: ...
    def add_expr(self, other: AffineExpr, sign: float) -> None: ...
    def scale(self, factor: float) -> None: ...
    def clone_expr(self) -> AffineExpr: ...
    def num_terms(self) -> int: ...
    def get_coeff(self, var: Variable) -> float: ...
    def set_sense(self, sense: Sense) -> None: ...
    def clear_sense(self) -> None: ...
    def set_name(self, name: str) -> None: ...
    def clear_name(self) -> None: ...
    def items(self) -> list[tuple[Variable, float]]: ...
    def keys(self) -> list[Variable]: ...
    def values(self) -> list[float]: ...
    def value(self) -> float | None: ...
    def var_name_coeffs(self) -> list[tuple[str, float]]: ...
    def terms_with_variables(self, model: Model) -> list[tuple[Variable, float]]: ...
    def combine_sense(self, other_sense: Sense | None, sign: float) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class Model:
    """High-level model handle exposed to Python."""

    def __init__(self, name: str | None = None) -> None: ...
    @property
    def num_variables(self) -> int: ...
    @property
    def num_constraints(self) -> int: ...
    def add_variable(
        self, name: str, lb: float, ub: float, category: Category
    ) -> Variable: ...
    def add_variables_batch(
        self, names: list[str], lb: float, ub: float, category: Category
    ) -> list[Variable]: ...
    def add_constraint(
        self,
        name: str,
        coeffs: list[tuple[Variable, float]],
        rhs: float,
        sense: Sense,
    ) -> Constraint: ...
    def set_objective(self, expr: AffineExpr) -> None: ...
    def set_sense(self, sense: ObjSense) -> None: ...
    def clear_objective(self) -> None: ...
    def get_variable(self, id: int) -> Variable: ...
    def list_variables(self) -> list[Variable]: ...
    def list_constraints(self) -> list[Constraint]: ...
    def get_objective(self) -> AffineExpr | None: ...
    def get_sense(self) -> ObjSense: ...
    def summary(self) -> str: ...
    def set_variable_values(self, values: list[tuple[int, float]]) -> None: ...
    def set_variable_djs(self, values: list[tuple[int, float]]) -> None: ...
    def set_constraint_pis(self, values: list[tuple[int, float]]) -> None: ...
    def set_constraint_slacks(self, values: list[tuple[int, float]]) -> None: ...
    def set_variable_values_by_name(self, values: dict[str, float]) -> None: ...
    def set_variable_djs_by_name(self, values: dict[str, float]) -> None: ...
    def set_constraint_pis_by_name(self, values: dict[str, float]) -> None: ...
    def set_constraint_slacks_by_name(self, values: dict[str, float]) -> None: ...
    def constraints_dict(self) -> list[tuple[str, Constraint]]: ...
    def variables_dict(self) -> list[tuple[str, Variable]]: ...
    def get_constraint_by_name(self, name: str) -> Constraint | None: ...
