repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.1.0
    hooks:
    -   id: pyupgrade
        args: [--py37-plus]
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.4
    hooks:
    -   id: ruff
        args: [--exit-non-zero-on-fix]